### ISSUE TITLE
state doesn't have param

### ISSUE THREAD

**Issue by constantx** [kriasoft/react-routing#6] opened 2015-08-03 04:04 UTC
<img width="548" alt="recipes" src="https://cloud.githubusercontent.com/assets/113969/9030634/071e1e88-395a-11e5-93e8-039ea9749805.png">

I'm expecting `state.params.recipeId`, but `params` doesn't exist on the `state` object.

**Comment by lehneres** [comment] 2015-08-06 06:28
seems to be solved in 0.0.4

**Comment by koistya** [comment] 2015-08-06 07:35
Yep, this one is fixed in 0.0.4

**Comment by maysale01** [comment] 2015-10-14 23:39
Issue still persists,

```

**Comment by maysale01** [comment] 2015-10-15 01:30
The issue is that `/lib/` doesn't contain 0.0.4 when you do `npm install react-routing`. If I clone this repo and run `npm run build` and copy the lib folder to my project it works.

**Comment by maysale01** [comment] 2015-10-22 09:12
Fixed in 0.0.5 This can be closed.

**Closed** 2015-10-22 09:37 UTC
